# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: election.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65lection.proto\"J\n\x0f\x45lectionMessage\x12\x10\n\x08senderId\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x17\n\x0fparticipant_ids\x18\x03 \x03(\x05\"(\n\x10\x45lectionResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x32\x46\n\x08\x45lection\x12:\n\x13sendElectionMessage\x12\x10.ElectionMessage\x1a\x11.ElectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'election_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONMESSAGE']._serialized_start=18
  _globals['_ELECTIONMESSAGE']._serialized_end=92
  _globals['_ELECTIONRESPONSE']._serialized_start=94
  _globals['_ELECTIONRESPONSE']._serialized_end=134
  _globals['_ELECTION']._serialized_start=136
  _globals['_ELECTION']._serialized_end=206
# @@protoc_insertion_point(module_scope)
